spring:
  rabbitmq:
    host: ec2-54-207-38-164.sa-east-1.compute.amazonaws.com
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        input:
          destination: product
          binder: rabbit
        output:
          destination: product
          binder: rabbit